/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2023-03-30 04:19:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');


    if (request.getSession().getAttribute("idUser") == null) {
        response.sendRedirect("Login.jsp");
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css\"\n");
      out.write("              integrity=\"sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==\"\n");
      out.write("              crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"css/Homepage.css\">  \n");
      out.write("        <link rel=\"stylesheet\" href=\"css/Toast.css\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div class=\"wrapper\">\n");
      out.write("            <div class=\"app\">\n");
      out.write("                <header class=\"heading\">Todo List</header>\n");
      out.write("                <input style=\"display: none\" id=\"ID_USER\" value=\"");
      out.print( session.getAttribute("idUser"));
      out.write("\"/>\n");
      out.write("                <div class=\"searchTodo_filterTodo\">\n");
      out.write("                    <div class=\"searchTodo\">\n");
      out.write("                        <input type=\"text\" name=\"search_todo\" class=\"search_todo\" placeholder=\"Find your todo...\" />\n");
      out.write("                        <button style=\"display: inline-block\" class=\"btn btn_searchTodo\">Search</button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"filterTodo\">\n");
      out.write("                        <div>\n");
      out.write("                            <select class=\"statusTodo\">\n");
      out.write("                                <option value=\"\">All</option>\n");
      out.write("                                <option value=\"1\">Complete</option>\n");
      out.write("                                <option value=\"0\">Incomplete</option>\n");
      out.write("                            </select>\n");
      out.write("                            <i class=\"fa-solid fa-arrow-down arrow-to-bottom\"></i>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"Todos\">\n");
      out.write("                    <ul class=\"list_todo\"></ul>\n");
      out.write("                    <div class=\"imgEmptyList\">\n");
      out.write("                        <img src=\"img/emptyList.png\" alt=\"\"/>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"addTodo_wrapper\">\n");
      out.write("                        <button id=\"btn-openModal\" class=\"btn addTodo\" type=\"button\">\n");
      out.write("                            <i class=\"fa-solid fa-plus\"></i>\n");
      out.write("                            &nbsp;&nbsp;\n");
      out.write("                            <span>Add Todo</span>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal_wrapper modalWrapperTodo\">\n");
      out.write("            <div class=\"modal\">\n");
      out.write("                <h3 class=\"titleModal title-add\">ADD TODO</h3>   \n");
      out.write("                <h3 class=\"titleModal title-details\">DETAILS TODO</h3>\n");
      out.write("                <form class=\"form-todo\">\n");
      out.write("                    <input id=\"idTodoFormUpdate\" type=\"text\"style=\"display: none\"/>\n");
      out.write("                    <div class=\"form-item\">\n");
      out.write("                        <label for=\"name\" class=\"label_modal\">Name: </label>\n");
      out.write("                        <br />\n");
      out.write("                        <input required=\"true\" name=\"titleTodo\" type=\"text\" class=\"input_modal\" id=\"titleTodo\"/>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- -->\n");
      out.write("                    <div class=\"form-item\">\n");
      out.write("                        <label for=\"note\" class=\"label_modal\">Note: </label>\n");
      out.write("                        <br />\n");
      out.write("                        <textarea name=\"noteTodo\" id=\"noteTodo\" class=\"input_modal\" rows=\"6\"></textarea>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- -->\n");
      out.write("                    <div class=\"dateWrapper\">\n");
      out.write("                        <p class=\"dateItem\">Ngày tạo:&nbsp;\n");
      out.write("                            <span class=\"date_createAt\"></span>\n");
      out.write("                        </p>                              \n");
      out.write("                        <p class=\"dateItem\">Chỉnh sửa lần cuối:&nbsp;\n");
      out.write("                            <span class=\"date_updateAt\">--/--/--</span>\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- -->\n");
      out.write("                    <div class=\"group-btn\">\n");
      out.write("                        <button class=\"btn btn_success\" id=\"btn-AddTodo\" type=\"button\">Add todo</button>\n");
      out.write("                        <button class=\"btn btn_info\" id=\"btn-UpdateTodo\" type=\"button\">Update todo</button>\n");
      out.write("                        <button class=\"btn btn_dangerous\" id=\"btn-closeModal\" type=\"button\">Cancel</button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal_wrapper modalWrapperUser\">\n");
      out.write("            <div class=\"modal modalUser\">\n");
      out.write("                <h3 style=\"display: block\" class=\"titleModal\">INFO USER</h3>   \n");
      out.write("                ");
      out.write("\n");
      out.write("                <form class=\"form-infoUser\">\n");
      out.write("                    <div class=\"form-item\">\n");
      out.write("                        <label for=\"userName\" class=\"label_modal\">Username: </label>\n");
      out.write("                        <br />\n");
      out.write("                        <input name=\"userName\" disabled=\"true\" type=\"text\" class=\"input_modal\"  value=\"");
      out.print( session.getAttribute("userName"));
      out.write("\"/>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- -->\n");
      out.write("                    <div class=\"form-item\">\n");
      out.write("                        <label for=\"password\" class=\"label_modal\">Password: </label>\n");
      out.write("                        <br />\n");
      out.write("                        <input name=\"password\" disabled=\"true\" type=\"password\" class=\"input_modal\" value=\"");
      out.print( session.getAttribute("password"));
      out.write("\"/>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"group-btn\">\n");
      out.write("                        <button style=\"display: block\" class=\"btn btn_info\" id=\"btn-UpdateUser\" type=\"button\">Update</button>\n");
      out.write("                        <button style=\"display: block\" class=\"btn btn_dangerous btn-closeModalUser\"   type=\"button\">Cancel</button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("                ");
      out.write("\n");
      out.write("                <form class=\"form-updateUser\">\n");
      out.write("                    <!-- -->\n");
      out.write("                    <div class=\"form-item\">\n");
      out.write("                        <label for=\"password\" class=\"label_modal\">Current Password: </label>\n");
      out.write("                        <br />\n");
      out.write("                        <input name=\"currentPassword\" type=\"password\" class=\"input_modal\"   />\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-item\">\n");
      out.write("                        <label for=\"password\" class=\"label_modal\">New Password: </label>\n");
      out.write("                        <br />\n");
      out.write("                        <input name=\"newPassword\" type=\"password\" class=\"input_modal\"   />\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-item\">\n");
      out.write("                        <label for=\"password\" class=\"label_modal\">Confirm Password: </label>\n");
      out.write("                        <br />\n");
      out.write("                        <input name=\"confirmPassword\" type=\"password\" class=\"input_modal\"   />\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"group-btn\">\n");
      out.write("                        <button style=\"display: block\" class=\"btn btn_success\" id=\"btn-SaveUser\" type=\"button\">Save</button>\n");
      out.write("                        <button style=\"display: block\" class=\"btn btn_dangerous btn-closeModalUser\"  type=\"button\">Cancel</button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>     \n");
      out.write("        <div id=\"toast_wrap\"></div>\n");
      out.write("        <div class=\"infoUserWrapper\">\n");
      out.write("            <div class=\"infoUser\">\n");
      out.write("                <img src=\"https://source.unsplash.com/random/500x500?sig=1002202810\" />\n");
      out.write("                <p class=\"\">");
      out.print( session.getAttribute("userName"));
      out.write("</p>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <button class=\"sign-out\" id=\"btn-signOut\">\n");
      out.write("                <i style=\"margin-right: 6px\" class=\"fa-solid fa-right-from-bracket\"></i>\n");
      out.write("                Sign out\n");
      out.write("            </button>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js\" integrity=\"sha512-pumBsjNRGGqkPzKHndZMaAG+bir374sORyzM3uulLV14lN5LyykqNk8eEeUlUkB3U0M4FApyaHraT65ihJhDpQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\n");
      out.write("    <script src=\"js/Homepage.js\"></script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
